Template matching key time
Ratoone/music_sheet_reader pull request #3
Opened 2020-05-09 17:36 UTC by Ratoone

Introduced generic multiscale template matching. This was applied to clef and time signature detection. Added template and sample images to the project

2020-05-10 09:27 UTC, gormasab commented on music_detection/staff.py
> +                self.time_signature = time
pls split this in another function

2020-05-10 10:33 UTC, gormasab requested changes
thanks for the code. However, next time more comments are expected. You don't always accompany your code to explain it.

2020-05-10 10:33 UTC, gormasab commented on music_detection/utils/template_matching.py
> +        if found is None or confidence > found[0]:
u have to write comments in ur code everywhere, for more information look at rey's nice codes.

2020-05-10 10:33 UTC, gormasab commented on music_detection/utils/template_matching.py
> +    return score, position
pls change score to some other name to avoid confusion.

2020-05-11 13:12 UTC, T3lchar commented
Looks good to me, consider commenting your code anyway :)

2020-05-11 13:12 UTC, jrmsgr approved these changes

2020-05-11 13:13 UTC, Ratoone commented
It is commented :)). Please show me where more comments are needed, and I will gladly add them

2020-05-11 13:46 UTC, gormasab approved these changes
I approved but I kindly request for more comments next time.

2020-05-11 14:22 UTC, merged