Midi reconstruction
Ratoone/music_sheet_reader pull request #7
Opened 2020-05-25 13:52 UTC by T3lchar

Added functions in the utils folder to convert a Staff object into a MIDI file.
For a detailed example, check examples/midi_encoding. Don't hesitate to play the resulting file, result.mdi !

2020-05-26 11:59 UTC, Ratoone requested changes

2020-05-26 11:59 UTC, Ratoone commented on music_detection/note.py
> +            self.duration = args[2]
Interesting choice of constructor, but what about a constructor with default values?

2020-05-26 11:59 UTC, Ratoone commented on music_detection/utils/midi_functions.py
> +def get_time_signature_values(staff : Staff) -> int :
I would suggest passing only the time signature, as you don't need the whole staff object for this

2020-05-26 11:59 UTC, Ratoone commented on music_detection/utils/midi_functions.py
> +#        a list of them as input
Either that, or have a class MidiWriter, and after initialization you append staff by staff, exporting the file only after the last one

2020-05-27 14:32 UTC, T3lchar commented on music_detection/utils/midi_functions.py
> +#        a list of them as input
I did as you told and created a MIDIWriter class that takes in charge all the process

2020-05-27 14:33 UTC, T3lchar commented on music_detection/utils/midi_functions.py
> +def get_time_signature_values(staff : Staff) -> int :
I did the modification, check it out

2020-05-27 14:33 UTC, T3lchar commented on music_detection/note.py
> +            self.duration = args[2]
Modified the constructor so that it has default values

2020-06-02 12:24 UTC, Ratoone approved these changes

2020-06-02 12:24 UTC, merged